name: CMake

on:
  push:
  pull_request:
  release:
    types: [created]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.name}}
    strategy:
      matrix:
        include:
          - name: Cosmic Unicorn
            board: cosmic
            cmake-args: '-DDISPLAY_PATH=display/cosmic/cosmic_unicorn.cmake'
          - name: Galactic Unicorn
            board: galactic
            cmake-args: '-DDISPLAY_PATH=display/galactic/galactic_unicorn.cmake'

    runs-on: ubuntu-20.04

    env:
      PICO_SDK_PATH: $GITHUB_WORKSPACE/pico-sdk
      PIMORONI_PICO_LIBS: $GITHUB_WORKSPACE/pimoroni-pico
      RELEASE_FILE: ${{matrix.board}}-blunicorn-${{github.event.release.tag_name || github.sha}}
      RELEASE_PATH: $GITHUB_WORKSPACE/install

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        path: project

    # Checkout the Pico SDK
    - name: Checkout Pico SDK
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true

    # Checkout the Pico SDK
    - name: Checkout Pico Extras
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-extras
        path: pico-extras
        submodules: true

    # Linux deps
    - name: Install deps
      run: |
        sudo apt update && sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/project -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCPACK_PACKAGE_FILE_NAME=${{env.RELEASE_FILE}} -DPICO_EXTRAS_PATH=$GITHUB_WORKSPACE/pico-extras -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk -DPICO_BOARD=pico_w -DCMAKE_INSTALL_PREFIX=`pwd`/install ${{matrix.cmake-args}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE -j 2

    - name: Prepare Artifact
      if: github.event_name != 'release'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --target install -j 2

    - name: Upload Artifact
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.RELEASE_FILE}}
        path: ${{runner.workspace}}/build/install

    - name: Build Release Packages
      if: github.event_name == 'release'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --target package -j 2

    - name: Upload .zip
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: ${{runner.workspace}}/build/${{env.RELEASE_FILE}}.zip
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.RELEASE_FILE}}.zip
        asset_content_type: application/zip

    - name: Upload .tar.gz
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: ${{runner.workspace}}/build/${{env.RELEASE_FILE}}.tar.gz
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.RELEASE_FILE}}.tar.gz
        asset_content_type: application/octet-stream
